@startuml

!define RELATION_ENTITY #FCE4D6-F8CBAD
!define RELATION_MARK_COLOR FFAA00

/'
デフォルトのスタイルを設定
'/
skinparam class {
    BorderColor Black
}

package "サンプル" as sample  {
    entity "{テーブル名}" as samples <{テーブルの概要}>  {
        + {カラム名}:{型} [{属性}] ({カラムの概要}) 緑丸は主キー
        --
        # {カラム名} [FK({外部キーのテーブル名}:{外部キーのカラム名}, OU:{on update(default=RESTRICT)} OD:{on delete(default=RESTRICT})] ({カラムの概要}) 黄色菱形は外部キー
        - {カラム名} [{制約}] ({カラムの概要}) 赤四角はハッシュ化
        ~ {カラム名} [{制約}] ({カラムの概要}) 青三角は暗号化
        {カラム名}:{型} [{制約}] ({カラムの概要})
    }
}

package "Aegis ER図" as aegis_erd {
    entity "users" as users <ユーザー> {
        + id:int [PK, AI, UN] (ID)
        ---
        ~ email:varchar(255) [UQ, NN] (メールアドレス)
        - email_hash:varchar(255) [UQ, NN] (メールアドレス)
        - password:varchar(255) [NN] (パスワード)
        ~ sei:varchar(255) [NN] (姓)
        ~ sei_kana:varchar(255) [NN] (姓カナ)
        ~ mei:varchar(255) [NN] (名)
        ~ mei_kana:varchar(255) [NN] (名カナ)
        - tel:varchar(255) [UQ, NN] (電話番号)
        - tel_hash:varchar(255) [UQ, NN] (電話番号)
        ~ birthday:date(255) (生年月日)
        points:int [NN, default:5000] (イージスポイント)
        remember_token:varchar(100) (自動ログイントークン)
        is_receive_notification_mail:tinyint [NN, default:1] (メンションメールを受け取るか)
        is_working:tinyint(1) [NN, default:0] (aegis経由で働いているかどうか)
        is_admin:tinyint(1) [NN, default:0] (管理者権限)
        is_new:tinyint(1) [NN, default:1] (新規:1か既存:0か)
        remarks:string(1) [OD:SETNULL] (備考欄)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
        deleted_at:datetime (削除日時)
    }

    entity "skills" as skills <スキル> {
        + id:int [PK, AI, UN] (ID)
        ---
        name:varchar(255) [NN, UQ] (スキル名)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "agents" as agents <エージェント> {
        + id:int [PK, AI, UN] (ID)
        ---
        name:varchar(255) [NN, UQ] (スキル名)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "stations" as stations <駅名> {
        + id:int [PK, AI, UN] (ID)
        ---
        # area_id [FK(area:id), OD:SETNULL] (エリアID)
        name:varchar(255) [NN, UQ] (駅名)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "areas" as areas <エリア名> {
        + id:int [PK, AI, UN] (ID)
        ---
        name:varchar(255) [NN, UQ] (エリア名)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "notes" as notes <お知らせ> {
            + id:int [PK, AI, UN] (ID)
            ---
            title:varchar(255) [NN] (タイトル)
            contents:text [NN] (内容)
            created_at:datetime [NN] (登録日時)
            updated_at:datetime [NN] (更新日時)
    }

    entity "projects" as projects <案件> {
        + id:int [PK, AI, UN] (ID)
        ---
        # station_id [FK(station:id), UIDX(1), OD:SETNULL] (駅名ID)
        # agent_id [FK(agent:id), UIDX(1), OD:SETNULL] (エージェントID)
        name:varchar(255) [NN] (案件名)
        min_unit_price:int (最小案件単価)
        max_unit_price:int [NN] (最大案件単価)
        min_operation_time:int (最小稼働時間)
        max_operation_time:int [NN] (最大稼働時間)
        description:text [NN] (案件概要)
        required_condition:text (必須条件)
        better_condition:text (尚可条件)
        work_start:time (勤務開始時間)
        work_end:time (勤務終了時間)
        weekly_attendance:int (出勤回数/週)
        feature:text (特徴)
        place: varchar(255) [NN] (勤務地)
        decided:tinyint(1) [NN, default:0] (案件が決まったかどうか)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "rel_projects_skills" as rel_projects_skills <案件・スキル> <<R, RELATION_MARK_COLOR>> RELATION_ENTITY {
        + id:int [PK, AI, UN] (ID)
        ---
        # project_id [FK(projects:id), UIDX(1), OD:CASCADE] (案件ID)
        # skill_id [FK(skills:id), UIDX(2), OD:CASCADE] (スキルID)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    } 

    entity "positions" as positions <ポジション> {
        + id:int [PK, AI, UN] (ID)
        ---
        name:varchar [NN, UQ] (配置ポジション名) 
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "rel_positions_projects" as rel_positions_projects <ポジション・案件> <<R, RELATION_MARK_COLOR>> RELATION_ENTITY {
        + id:int [PK, AI, UN] (ID)
        ---
        # position_id [FK(positions:id), UIDX(1), OD:CASCADE] (ポジションID)
        # project_id [FK(projects:id), UIDX(2), OD:CASCADE] (案件ID)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "rel_levels_skills_users" as rel_levels_skills_users <レベル・スキル・ユーザー> <<R, RELATION_MARK_COLOR>> RELATION_ENTITY {
        + id:int [PK, AI, UN] (ID)
        ---
        # user_id [FK(users:id), UIDX(1) , OD:CASCADE] (ユーザーID)
        # skill_id [FK(skills:id), UIDX(2) , OD:CASCADE] (スキルID)
        # level_id [FK(levels:id), UIDX(3) , OD:CASCADE] (レベルID)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "levels" as levels <レベル> {
        + id:int [PK, AI, UN] (ID)
        ---
        level:varchar(255) [NN, UQ] (レベル)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "applications" as applications <応募> <<R, RELATION_MARK_COLOR>> RELATION_ENTITY {
        + id:int [PK, AI, UN] (ID)
        ---
        user_id [FK(users:id), UIDX(1) , OD:CASCADE] (ユーザーID)
        project_id [FK(projects:is), UIDX(2) , OD:CASCADE] (案件ID)
        interview_date:datetime [NN] (面談日)
        operation_start_month:datetime [NN] (営業開始月)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "assignment" as assignment <稼働> <<R, RELATION_MARK_COLOR>> RELATION_ENTITY {
        + id:int [PK, AI, UN] (ID)
        ---
        user_id [FK(users:id), UIDX(1) , OD:CASCADE] (ユーザーID)
        project_id [FK(projects:is), UIDX(2) , OD:CASCADE] (案件ID)
        assignment_start_date:datetime [NN] (稼働開始日)
        assignment_end_date:datetime [NN] (稼働終了日)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }

    entity "status" as status <ステータス> <<R, RELATION_MARK_COLOR>> RELATION_ENTITY {
            + id:int [PK, AI, UN] (ID)
            ---
            user_id [FK(users:id), UIDX(1) , OD:CASCADE] (ユーザーID)
            project_id [FK(projects:is), UIDX(2) , OD:CASCADE] (案件ID)
            status:int [NN] (申し込み状況)
            created_at:datetime [NN] (登録日時)
            updated_at:datetime [NN] (更新日時)
    }

    entity "points_histories" as points_histories <ポイント履歴> {
        + id:int [PK, AI, UN] (ID)
        ---
        user_id [FK(users:id), OD:CASCADE] (ユーザーID)
        points:int [NN] (イージスポイント)
        created_at:datetime [NN] (登録日時)
        updated_at:datetime [NN] (更新日時)
    }
}

users       --ri--o{    rel_levels_skills_users
levels      --le--|{    rel_levels_skills_users
skills      --do--|{    rel_levels_skills_users

skills      --up--|{    rel_projects_skills
projects    --do--|{    rel_projects_skills

projects    --do--|{    rel_positions_projects
positions   --up--|{    rel_positions_projects

agents      --ri--|{    projects

stations    --le--|{    projects

areas       --le--|{    stations

users       --up--o{    applications
projects    --do--o{    applications

users       --up--o{    status
projects    --do--o{    status

users       --up--o{    assignment
projects    --do--o{    assignment

users       --le--|{    points_histories
@enduml

