version: "3.8"
services:
  nginx:
    image: nginx:1.18-alpine
    ports:
      - 8090:80
    volumes:
      - ./app:/aegis
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /aegis

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start

  php:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    tty: true
    stdin_open: true
    environment:
      LOG_CHANNEL: 'stderr'
    volumes:
      - ./app:/aegis
  
  mysql:
    image: mysql:8.0
    environment:
        MYSQL_DATABASE: aegis
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: developer
        MYSQL_PASSWORD: password
        TZ: Asia/Tokyo
    command: --port 4000
    ports:
        - 4000:4000
    volumes:
        - ./infra/mysql/data:/docker-entrypoint-initdb.d
  redis:
    image: "redis:latest"
    ports:
      - "6381:6379"
    volumes:
      - "./data/redis:/data"
