apiVersion: v1
kind: Secret
metadata:
  name: aegis-prod-secret
data:
  HASH_EMAIL_ALGO: U0hBNTEy
  HASH_EMAIL_SALT: ZXVkaGZrd29la3RrZWlkdw==
  HASH_ACCOUNT_ALGO: U0hBNTEy
  HASH_ACCOUNT_SALT: ZmxzaWVtbmI4NGpzb3Znag==
  DB_CONNECTION: bXlzcWw=
  DB_HOST: MTAuMTM3LjE0NC4z 
  DB_PORT: MzMwNg==
  DB_DATABASE: YWVnaXM=
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: QzR2amJLOE9JeU96SnN6RA==
  APP_KEY: YmFzZTY0OkhQUENEK2RrelhHbVpKdldncngwVzBrL0NweENMYnZjQzJtb1pjc2Y3QnM9
